# Check build of OpenKNX OFM with Reference OAM (merging/building of OpenKNX knxprod + build of full releases)
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2025 Cornelius Koepp

name: DFA-check
run-name: Check OFM-Homematic Build

on: [push]

jobs:
  check:
    name: Check '${{ matrix.target }}' in '${{ matrix.oam }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - oam: OAM-Homematic
            # knxprod_xml: HomematicGW-Release
            target: Release

        # # [BUILD]: all build targets
        # target:
        #   - DFA16-Release
        # #  - ""
        #
        # # [REF]: same commit and (newest on) branch
        # # restore_branch:
        # #   - false
        # #   - true

    uses: ./.github/workflows/openknx-ofm-check.yml
    with:
      KNXPROD_PREFIX: HomematicGW
      oam: ${{ matrix.oam }}
      target: ${{ matrix.target }}
      # restore_branch: ${{ matrix.restore_branch }}