# Check build of OpenKNX OFM with Reference OAM (merging/building of OpenKNX knxprod + build of full releases)
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2025 Cornelius Koepp

name: openknx-ofm-check
run-name: Check OpenKNX OFM Build in Reference OAM

on:
  workflow_call:
    inputs:
      oam:
        required: true
        type: string
      target:
        required: true
        type: string
      # restore_branch:
      #   required: true
      #   type: boolean
      KNXPROD_PREFIX:
        required: true
        type: string

jobs:
  oam-build:
    runs-on: ubuntu-latest
    env:
      PRODUCER_VERSION: 3.8.0
      PRODUCER_URL: https://github.com/OpenKNX/OpenKNXproducer/releases/download/v3.8.0/OpenKNXproducer-3.8.0.zip
      PRODUCER_CHECKSUM: 34d708df99dafd2cbb8a1b5fc7e31d08a570395f52dcbb37551139d731bf3d3b2682f7d3ab6f57ffea82d45c24838d2a46b5a746e32e02db7284aa4e3e404802
      PRODUCER_FILENAME: OpenKNXproducer-${PRODUCER_VERSION}.zip

    name: Build '${{ inputs.target }}' ${{ inputs.restore_branch && 'branch' || 'commit' }}
    steps:
      # DO this after restore the use current commit
      # - uses: actions/checkout@v4
      #   with:
      #     path: OFM-DFA

      - name: Check for Same Name Branch in Reference OAM
        id: oam_branch
        run: |
          BRANCH="v1dev"
          EXISTS=$(git ls-remote --heads https://github.com/openknx/${{ inputs.oam }}.git ${{ github.ref_name }} | wc -l)
          if [ "$EXISTS" -gt 0 ]; then
            BRANCH="${{ github.ref_name }}"
          fi
          echo "ref_name=$BRANCH" >> $GITHUB_OUTPUT
          echo "Selected branch: $BRANCH"

      - name: Checkout Reference OAM
        uses: actions/checkout@v4
        with:
          repository: openknx/${{ inputs.oam }}
          ref: ${{ steps.oam_branch.outputs.ref_name }}
          path: ${{ inputs.oam }}

      # - name: DEBUG paths
      #   run: |
      #     pwd
      #     find

      - name: Restore OAM
        shell: pwsh
        run: |
          cd ${{ inputs.oam }}/restore 
          ./Restore-Dependencies.ps1

      - name: Restore Current OFM Commit
        uses: actions/checkout@v4
        with:
          # ref: ${{ github.ref_name }}
          path: OFM-DFA

      - name: Extract OFM-version (major.minor) from library.json
        id: get_version
        run: |
          cd OFM-DFA
          VERSION=$(jq -r '.version' library.json)
          VERSION_MAJOR_MINOR=$(echo "$VERSION" | grep -oE '^[0-9]+\.[0-9]+')
          echo "VERSION_MAJOR_MINOR=$VERSION_MAJOR_MINOR" >> $GITHUB_ENV
          echo "OFM-Version: $VERSION_MAJOR_MINOR"

      - name: Patch OAM to Current OFM-Version ${{ env.VERSION_MAJOR_MINOR }}
        run: |
          cd ${{ inputs.oam }}
          sed -i 's/\(<op:config name="%DFA_VerifyVersion%"[ ]*value="\)[^"]*\(".*\/>\)/\1'"$VERSION_MAJOR_MINOR"'\2/' src/${{inputs.KNXPROD_PREFIX}}.conf.xml
          echo "Set %DFA_VerifyVersion% to $VERSION_MAJOR_MINOR"

      - name: Download OpenKNXproducer ${{ env.PRODUCER_VERSION }} and Verify
        run: |
          mkdir OpenKNXproducer
          cd OpenKNXproducer
          echo "${PRODUCER_CHECKSUM} *${PRODUCER_FILENAME}" > OpenKNXproducer.checksum
          wget -q "${PRODUCER_URL}" -O "${PRODUCER_FILENAME}"
          sha512sum "${PRODUCER_FILENAME}"
          sha512sum -c OpenKNXproducer.checksum
      - name: Unzip OpenKNXproducer and Make Executable
        run: |
          cd OpenKNXproducer
          unzip "${PRODUCER_FILENAME}" || test -f tools/Linux/OpenKNXproducer
          chmod u+x tools/Linux/OpenKNXproducer
      - name: Check OpenKNXproducer
        run: OpenKNXproducer/tools/Linux/OpenKNXproducer version || echo Ignore OpenKNXproducer always returning 1...

      - name: Install OpenKNXproducer
        run: cp -av OpenKNXproducer/tools/Linux/OpenKNXproducer /usr/local/bin/OpenKNXproducer

      - name: Create knxprod
        run: |
          cd ${{ inputs.oam }}
          OpenKNXproducer create --Debug -h include/knxprod.h src/${{inputs.KNXPROD_PREFIX}}${{ inputs.target != '' && format('-{0}', inputs.target) || '' }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv ~/.platformio/penv
          source ~/.platformio/penv/bin/activate
          pip install platformio

      - name: OpenKNX Release Build
        run: |
          cd ${{ inputs.oam }}
          pwsh ./scripts/Build-Release.ps1 ${{ inputs.target }}

      - name: Show Changed Files
        run: |
          cd ${{ inputs.oam }}
          git diff
